### ISSUE TITLE
Feature Request: Add ability to add custom field transformers

### ISSUE THREAD

**Issue by curtishenson** [samuelreichor/craft-query-api#3]
Was able to test this real quick in a new Astro project, it was super easy to get working! The API looks really well thought out, and docs already? Amazing.

We use the Hyper plugin pretty extensively and I think it would need a custom field transformer to return content that is usable. I'm sure that would wind up being the case for other field plugins as well.

My thought was to add an event so plugins and modules could register their own field transformers.

**Comment by samuelreichor** [comment]
Thank you for taking the try it out and for the kind words! I’ll take a closer look. An event system for registering custom field transformers could definitely add a lot of flexibility. 👍

**Comment by samuelreichor** [comment]
@curtishenson I’ve added the `EVENT_REGISTER_FIELD_TRANSFORMERS`, allowing you to override or add transformers based on the field's class. I’ll update the documentation soon, but here’s a quick overview of how it works:

### **1. Initialize the Event Listener**
You can use the `EVENT_REGISTER_FIELD_TRANSFORMERS` to register your custom transformers. For example:

```php
use modules\queryapiextension\transformers\HyperTransformer;
use samuelreichoer\queryapi\transformers\BaseTransformer;
use samuelreichoer\queryapi\events\FieldTransformerEvent;

Event::on(
    BaseTransformer::class,
    BaseTransformer::EVENT_REGISTER_FIELD_TRANSFORMERS,
    function (FieldTransformerEvent $event) {
        $event->transformers[] = [
            'fieldClass' => 'verbb\hyper\fields\HyperField',
            'transformer' => HyperTransformer::class,
        ];
    }
);
```

### **2. Add Your Custom Transformer**
Here’s an example of a custom transformer implementation:

```php
<?php

namespace modules\queryapiextension\transformers;

use verbb\hyper\models\LinkCollection;

class HyperTransformer
{
    private LinkCollection $hyper;

    public function __construct(LinkCollection $hyper)
    {
        $this->hyper = $hyper;
    }

    /**
     * Transforms the Hyper field data.
     *
     * @return array
     */
    public function getTransformedData(): array
    {
        return [
            'metadata' => $this->getMetaData(),
            'linkText' => $this->hyper->text,
            'linkUrl' => $this->hyper->url,
            'linkTarget' => $this->hyper->target,
        ];
    }

    /**
     * Retrieves metadata from the Hyper field.
     *
     * @return array
     */
    protected function getMetaData(): array
    {
        return [
            'type' => $this->hyper->type,
        ];
    }
}
```

### **Additional Notes**
1. If you need to reuse or extend base logic, you can inherit your transformer class from the `BaseTransformer`.
2. The plugin relies on the `getTransformedData()` function to fetch the transformed data. Ensure this method exists in your transformer for compatibility.

Let me know if you have any questions or feedback!

**Comment by curtishenson** [comment]
Nice! Exactly what I was thinking. Thank you
